# Site settings
title: John Chittum
email: john.chittum@gmail.com
description: The Docker Hug Tutorial by John Chittum
baseurl: "/docker-hug-tutorial" # the subpath of your site, e.g. /blog/
twitter_username: basementhobo
github_username:  j5awry

# Build settings
markdown: kramdown

