version: "3.6"
services:
  pgdb:
    build: ./postgres
    volumes:
      - postgres_vol:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: iris
      POSTGRES_DB: iris
  iris:
    build: ./iris
    volumes:
      - ./iris/app:/var/lib/iris/app
    ports:
      - "8000:8000"
    environment:
      IRIS_USER: iris
      IRIS_PASS: ${IRIS_PASS}
    depends_on:
      - pgdb
volumes:
  postgres_vol: